test: workflows variable

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,25 +1,19 @@
 name: CD to Production
 
 on:
-    push:
+    pull_request:
         branches:
             - main
 
 jobs:
     deploy:
         runs-on: ubuntu-latest
+        environment: AWS-Dicoding
 
         steps:
-            - name: Deploy app
-              uses: appleboy/ssh-action@master
-              with:
-                  host: ${{ secrets.SSH_HOST }}
-                  username: ${{ secrets.SSH_USERNAME }}
-                  key: ${{ secrets.SSH_KEY }}
-                  port: ${{ secrets.SSH_PORT }}
-                  script: |
-                      cd ~/apps/forum-api-starter-project
-                      git pull origin main
-                      npm ci --omit=dev --no-audit --no-fund
-                      npm run migrate up
-                      pm2 restart forum-api
+            - name: Validate deployment secrets
+              run: |
+                  if [ -z "${{ secrets.SSH_USERNAME }}" ]; then
+                    echo "Error: SSH_USERNAME secret is not set."
+                    exit 1
+                  fi
